### ISSUE TITLE
Questions about the donor game

### ISSUE THREAD

**Issue by Computerlabrat** [smaTc/RemotePlayDetached#25]
Is the use of the donor temporary or permanent? Is there anyway I can replace this with the donor game's exe file. I'm asking because I'm wondering if I should use Rocket League as I never really play it any more since Epic took over and I believe I noticed it supports remote play together.  Also, are there any recommendations for free to play games with remote play together I could use?

**Comment by ooa113y** [comment]
The donation is "temporary" in the sense that you can get the original game back by verifying its files via Steam. Adding the original game to RPD itself may sort of work, if it's moved to a different location beforehand, but there's no guarantee and it will depend on the game itself, so would not recommed doing it.

As far as donor games go, [Spacewar](https://steamdb.info/app/480) is most definitely the ideal candidate. Spacewar isn't really a "game" as such, it's an example application Valve has published for developers to familiarize themselves with Steamworks feature (documented [here](https://partner.steamgames.com/doc/sdk/api/example), if you're interested in the exact details, but it's not required reading by any means). Being an example app, it has all the Steamworks features working, which includes Remote Play Together. And since it's not a "real" game, you, as a regular user, don't actually end up losing anything by sacrificing it for RPD.

But if you have a game that you just no longer play anymore, sure, that works. Any other free game with Remote Play Together enabled also does work. But you still do lose a real game that way, even if it's one you don't care for much.

**Comment by Computerlabrat** [comment]
Thanks. I think Spacewar is supposed to be the very first game, thus predating Pong. It might be a better choice of the two unless you're on Linux and you have Rocket League installed, but don't play it as I imagine Steam would just keep auto updating Rocket League now that I've thought about it.
